export const categoryKeyMap = {
  Adventure: "adventure",
  Beach: "beach",
  City: "city",
  Culture: "culture",
  Desert: "desert",
  "Sahara Tour": "saharaTour",
  "Camel Trekking": "camelTrekking",
  "Quad & Buggy": "quadBuggy",
  "Mountains & Hiking": "mountainsHiking",
  Surfing: "surfing",
  Wildlife: "wildlife",
  "Atlas Mountains": "atlasMountains",
  "Food & Culinary": "foodCulinary",
  "Medina Tours": "medinaTours",
  "Historical Sites": "historicalSites",
  Photography: "photography",
  "Luxury & Riads": "luxuryRiads",
  "Spa & Hammam": "spaHammam",
  "Day Trips": "dayTrips",
  Excursions: "excursions",
  Transport: "transport",
  "Events & Festivals": "eventsFestivals",
  Shopping: "shopping",
  "Guided Tours": "guidedTours",
  Sahara: "sahara",
};
