export const exclusionKeyMap = {
  "International flights": "internationalFlights",
  "Visa fees (if applicable)": "visaFees",
  "Passport & document fees": "passportDocumentFees",
  "Travel vaccinations": "travelVaccinations",
  "Personal expenses": "personalExpenses",
  "Tips & gratuities": "tipsGratuities",
  "Souvenirs & shopping": "souvenirsShopping",
  "Currency exchange fees": "currencyExchangeFees",
  "Lunches (unless specified)": "lunchesUnlessSpecified",
  "Dinners (unless specified)": "dinnersUnlessSpecified",
  "Alcoholic beverages": "alcoholicBeverages",
  "Laundry services": "laundryServices",
  "Room service charges": "roomServiceCharges",
  "Early check-in / late check-out": "earlyCheckInLateCheckOut",
  "Hotel minibar charges": "hotelMinibarCharges",
  "Excess baggage fees": "excessBaggageFees",
  "Porter / luggage handling fees": "porterLuggageHandlingFees",
  "Travel insurance (unless specified)": "travelInsuranceUnlessSpecified",
  "Medical expenses": "medicalExpenses",
  "Optional activities & excursions": "optionalActivitiesExcursions",
  "Entry fees not mentioned in the itinerary": "entryFeesNotMentioned",
  "Additional experiences not listed": "additionalExperiencesNotListed",
  "Phone calls & internet charges": "phoneCallsInternetCharges",
  "City tourist tax (paid directly at hotel)": "cityTouristTax",
};
