export const inclusionKeyMap = {
  "Hotel / Riad accommodation": "hotelRiadAccommodation",
  "Daily breakfast": "dailyBreakfast",
  "Half-board (breakfast & dinner)": "halfBoard",
  "Full-board (all meals included)": "fullBoard",
  "Airport pickup & drop-off": "airportPickupDropoff",
  "Air-conditioned transport": "airConditionedTransport",
  "Professional driver": "professionalDriver",
  "Licensed local tour guide": "licensedLocalTourGuide",
  "Fuel, tolls & parking fees": "fuelTollsParking",
  "Monument & attraction entry fees": "monumentAttractionEntryFees",
  "Guided city tours": "guidedCityTours",
  "Museum visits": "museumVisits",
  "Desert excursion": "desertExcursion",
  "Camel ride experience": "camelRideExperience",
  "Desert camp overnight stay": "desertCampOvernight",
  "Traditional Moroccan dinner": "traditionalMoroccanDinner",
  "Welcome tea ceremony": "welcomeTeaCeremony",
  "Cooking class with locals": "cookingClassWithLocals",
  "Lunch during excursions": "lunchDuringExcursions",
  "Street food tasting experience": "streetFoodTasting",
  "Surfing lessons": "surfingLessons",
  "Quad biking session": "quadBikingSession",
  "Buggy driving experience": "buggyDrivingExperience",
  Sandboarding: "sandboarding",
  "Mountain trekking guide": "mountainTrekkingGuide",
  "Boat cruise": "boatCruise",
  "Snorkeling equipment": "snorkelingEquipment",
  "Spa & hammam session": "spaHammamSession",
  "Massage session": "massageSession",
  "Beach club access": "beachClubAccess",
  "Professional photography session": "professionalPhotographySession",
  "24/7 travel assistance": "travelAssistance247",
  "Local SIM card / mobile data": "localSimCardMobileData",
  "Daily bottled water": "dailyBottledWater",
  "Personalized itinerary planning": "personalizedItineraryPlanning",
  "Multilingual support": "multilingualSupport",
  "Travel insurance": "travelInsurance",
  "Emergency assistance": "emergencyAssistance",
  "Child-friendly equipment": "childFriendlyEquipment",
  "Luxury desert camp upgrade": "luxuryDesertCampUpgrade",
  "Private driver service": "privateDriverService",
  "5-star hotel upgrade": "fiveStarHotelUpgrade",
  "Hot air balloon experience": "hotAirBalloonExperience",
  "Private yacht / boat trip": "privateYachtBoatTrip",
  "Helicopter transfer": "helicopterTransfer",
};
